#!/usr/bin/python
import subprocess
import bibtexparser
import struct
import re
from bibtexparser.bparser import BibTexParser
from bibtexparser.customization import convert_to_unicode

# DEFAULT CONFIG SECTION
document_dir = '/home/thorsten/uni/literatur'
bibfile = document_dir + '/' + 'refs.bib'
rofi_command = [ 'rofi' , '-dmenu', '-i' , '-eh', '2', '-no-custom' ]
rofi_command += [ '-lines', '10', '-normal-window' ]

# accepts a list of strings and returns the index of the selected menu entry
# or None otherwise
def call_rofi(entries):
    additional_args = [ '-sep', '\\0', '-format', 'i' ]
    proc = subprocess.Popen(rofi_command + additional_args,
                            stdin=subprocess.PIPE,
                            stdout=subprocess.PIPE)
    for e in entries:
        proc.stdin.write((e).encode('utf-8'))
        proc.stdin.write(struct.pack('B', 0))
    proc.stdin.close()
    answer = proc.stdout.read().decode("utf-8")
    # trim whitespace
    answer = re.sub('[ \n]', '', answer)
    if answer == '':
        return None
    else:
        return int(answer)

def fix_string(string):
    string = re.sub('[\s+]', ' ', string)
    string = re.sub('[\\\\{}]', '', string)
    return string

def reorder_author_name(author):
    parts = author.split(', ')
    parts.reverse()
    return ' '.join(parts)

def format_author(author):
    author = fix_string(author)
    authors = author.split(' and ')
    authors = [ reorder_author_name(i) for i in authors ]
    return ', '.join(authors)

# TODO: load user configuration here.

with open(bibfile) as bibtex_file:
    parser = BibTexParser()
    parser.customization = convert_to_unicode
    bib_database = bibtexparser.load(bibtex_file, parser=parser)
    menu = []
    for e in bib_database.entries:
        str = fix_string(e.get('title', e.get('ID', '?'))) + '\n'
        str += format_author(e.get('author', '?')) + ' ' + e.get('year', '')
        menu.append(str)
    print(call_rofi(menu))
    #print(bib_database.entries)
